rss_feed_urls={"world":"http://rss.cnn.com/rss/edition_world.rss",
                "technology":"http://rss.cnn.com/rss/edition_technology.rss",
                "science&space":"http://rss.cnn.com/rss/edition_space.rss",
                "Entertainment":"http://rss.cnn.com/rss/edition_entertainment.rss",
                "sports":"http://rss.cnn.com/rss/edition_sport.rss",
                "travel":"http://rss.cnn.com/rss/edition_travel.rss",
                "cricket":"https://feeds.feedburner.com/ndtvsports-cricket",
                "business":"https://feeds.feedburner.com/ndtvprofit-latest",
                "auto":"https://feeds.feedburner.com/carandbike-latest"}